#enable nodeRestriction admission controller on kube-apiserver:
# --enable-admission-plugins=NodeRestriction,ImagePolicyWebhook
# --disable-admission-plugins=AlwaysPullImages

#add nodelabel using kubeletconf:
ssh node01
    export KUBECONFIG=/etc/kubernetes/kubelet.conf
    k label node node01 node-restriction.kubernetes.io/two=123 # restricted
    k label node controlplane killercoda/two=123 # restricted by default on different node
    k label node node01 test/two=123 # works because not restricted

---------------------------------------------

#admission-config webhook full config steps:
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
  - name: ImagePolicyWebhook
    #path: eventconfig.yaml # can give the path to config file or can provide configh directly like below.
    configuration:
      imagePolicy:
        kubeConfigFile: <path-to-kubeconfig-file>
        allowTTL: 50
        denyTTL: 50
        retryBackoff: 500
        defaultAllow: true # if admission wehhook fails it will allow image to downloaed

#path for admission config file:
# /etc/kubernetes/admission/

#vi to kube-apiserver.yaml
# - --admission-control-config-file=/etc/kubernetes/admission/admission-config.yaml
# --enable-admission-plugins=NodeRestriction,ImagePolicyWebhook

# add volume for admission config file
# volumes:
   - name: admission-config
     hostPath: 
        path: /etc/kubernetes/admission
        type: DirectoryOrCreate 
# volumemounts:
   - name: admission-config
     mountPath: /etc/kubernetes/admission
     readOnly: true