#get etcd cert file locations:
cat /etc/kubernetes/manifests/kube-apiserver.yaml | grep etcd

# access secret using etcd
ETCDCTL_API=3 etcdctl --cert /etc/kubernetes/pki/apiserver-etcd-client.crt \
--key /etc/kubernetes/pki/apiserver-etcd-client.key \
--cacert /etc/kubernetes/pki/etcd/ca.crt get /registry/secrets/<ns_name>/<secret_name>

#encrypt etcd at rest:
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - aesgcm:
        keys:
        - name: key1
          secret: dGhpcy1pcy12ZXJ5LXNlYw==
    - identity: {} # dont need this after reencrypting all existing secrets

  # provide encryption provider config to kube-apiserver
  # --encryption-provider-config=/etc/kubernetes/etcd/encryption-config.yaml

  # add volume for encryption config
   volumes:
   - name: encryption-config
     hostPath:
        path: /etc/kubernetes/etcd
        type: DirectoryOrCreate
  #mount the volume for encryption config
  volumeMounts:
   - name: encryption-config
     mountPath: /etc/kubernetes/etcd
     readOnly: true
       
# command to reencrypt all secrets:
# kubectl get secrets -A -oyaml | kubectl replace -f -