apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: runsc-sandbox
handler: runsc



###### pod spec with runtimeClass name:
spec:
  runtimeClassName: runsc-sandbox


#dry run the pod:
k -n <ns> run <p_name> --image=nginx:1.19.2 --dry-run=client -o yaml

# and add following line:
spec:
  nodeName: cluster1-node2 # add
  runtimeClassName: gvisor   # add

#chech po running on gvisor or not 
kubectl exec non-sandbox-pod -- dmesg 

#stream the logs to file:
k -n <ns> exec <pod_name> > /opt/filename -- dmesg