#get ing from ns:
k -n <ns> get ing <ingress_name>  

# create tls secret:
 k -n team-pink create secret tls tls-secret --key tls.key --cert tls.crt

#create tls-ingress:
kubectl create ingress simple --rule="foo.com/bar=svc1:8080,tls=my-cert"  --dry-run=client -o yaml
or
#get existing ingress to update tls:
k -n team-pink get ing secure -oyaml > 15_ing_bak.yaml

#update hostname and add tls secret in ingress:
spec:
  tls:                            # add
    - hosts:                      # add
      - secure-ingress.test       # add
      secretName: tls-secret      # add
  rules:
  - host: secure-ingress.test