---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operations-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serviceaccount-operations-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: sa-api
  namespace: k97
roleRef:
  kind: ClusterRole
  name: operations-clusterrole
  apiGroup: rbac.authorization.k8s.io
---

#cluterrole binding with SA from namespace
k create clusterrolebinding <name> \
  --clusterrole=<clusterrole_name><e.g edit> \
  --serviceaccount=<namespace>:<serviceaccount_name>