apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-operations-clusterrole
  namespace: k97
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list","create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list"]


--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccount-pod-clusterrolebinding
  namespace: k97
subjects:
- kind: ServiceAccount
  name: sa-pod-api
- kind: User
  name: <user_name>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-operations-clusterrole
  apiGroup: rbac.authorization.k8s.io


# create role
kubectl -n applications create role <r_name> \
  --verb=create,delete \
  --resource=pods,deployments,statefulsets


# create role-binding
k -n applications create rolebinding <rb_name> --role <r_name> --user <user>